image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com


clone_base:
  script:
    - docker pull cgwalters/centosmin
    - docker tag cgwalters/centosmin:latest registry.gitlab.com/gbraad/centosmin:latest
    - docker push registry.gitlab.com/gbraad/centosmin:latest
  only:
    - master

build_ci:
  script:
    - curl https://ci.centos.org/job/atomic-dockerimage-centos-7/lastSuccessfulBuild/artifact/centosmin-7.tar.gz | docker import - registry.gitlab.com/gbraad/centosmin:ci7
    - docker push registry.gitlab.com/gbraad/centosmin:ci7
  only:
    - master
